version: '3.7'

services:
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_DB: safeboda
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432

  safe-boda:
    build:
      context: .
      args:
        - MIX_ENV=prod
    environment:
      - DB_URL=postgres
    ports:
      - 4000:4000
